INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.101', 'Compra para industrialização');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.102', 'Compra para comercialização');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.111', 'Compra para industrialização de mercadoria recebida anteriormente em consignação industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.113', 'Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.116', 'Compra para industrialização originada de encomenda para recebimento futuro');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.117', 'Compra para comercialização originada de encomenda para recebimento futuro');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.118', 'Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.120', 'Compra para industrialização, em venda à ordem, já recebida do vendedor remetente');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.121', 'Compra para comercialização, em venda à ordem, já recebida do vendedor remetente');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.122', 'Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.124', 'Industrialização efetuada por outra empresa');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.125', 'Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.126', 'Compra para utilização na prestação de serviço');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.151', 'Transferência para industrialização');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.152', 'Transferência para comercialização');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.153', 'Transferência de energia elétrica para distribuição');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.154', 'Transferência para utilização na prestação de serviço');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.201', 'Devolução de venda de produção do estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.202', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.203', 'Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.204', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.205', 'Anulação de valor relativo à prestação de serviço de comunicação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.206', 'Anulação de valor relativo à prestação de serviço de transporte');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.207', 'Anulação de valor relativo à venda de energia elétrica');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.208', 'Devolução de produção do estabelecimento, remetida em transferência');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.209', 'Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.251', 'Compra de energia elétrica para distribuição ou comercialização');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.252', 'Compra de energia elétrica por estabelecimento industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.253', 'Compra de energia elétrica por estabelecimento comercial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.254', 'Compra de energia elétrica por estabelecimento prestador de serviço de transporte');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.255', 'Compra de energia elétrica por estabelecimento prestador de serviço de comunicação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.256', 'Compra de energia elétrica por estabelecimento de produtor rural');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.257', 'Compra de energia elétrica para consumo por demanda contratada');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.301', 'Aquisição de serviço de comunicação para execução de serviço da mesma natureza');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.302', 'Aquisição de serviço de comunicação por estabelecimento industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.303', 'Aquisição de serviço de comunicação por estabelecimento comercial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.304', 'Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.305', 'Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.306', 'Aquisição de serviço de comunicação por estabelecimento de produtor rural');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.351', 'Aquisição de serviço de transporte para execução de serviço da mesma natureza');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.352', 'Aquisição de serviço de transporte por estabelecimento industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.353', 'Aquisição de serviço de transporte por estabelecimento comercial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.354', 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.355', 'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.356', 'Aquisição de serviço de transporte por estabelecimento de produtor rural');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.401', 'Compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.403', 'Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.406', 'Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.407', 'Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.408', 'Transferência para industrialização em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.409', 'Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.410', 'Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.411', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.414', 'Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.415', 'Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.451', 'Retorno de animal do estabelecimento produtor');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.452', 'Retorno de insumo não utilizado na produção');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.501', 'Entrada de mercadoria recebida com fim específico de exportação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.503', 'Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.504', 'Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.551', 'Compra de bem para o ativo imobilizado');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.552', 'Transferência de bem do ativo imobilizado');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.553', 'Devolução de venda de bem do ativo imobilizado');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.554', 'Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.555', 'Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.556', 'Compra de material para uso ou consumo');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.557', 'Transferência de material para uso ou consumo');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.601', 'Recebimento, por transferência, de crédito de ICMS');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.602', 'Recebimento, por transferência, de saldo credor de ICMS de outro estabelecimento da mesma empresa, para compensação de saldo devedor de ICMS');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.603', 'Ressarcimento de ICMS retido por substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.604', 'Lançamento do crédito relativo à compra de bem para o ativo imobilizado');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.901', 'Entrada para industrialização por encomenda');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.902', 'Retorno de mercadoria remetida para industrialização por encomenda');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.903', 'Entrada de mercadoria remetida para industrialização e não aplicada no referido processo');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.904', 'Retorno de remessa para venda fora do estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.905', 'Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.906', 'Retorno de mercadoria remetida para depósito fechado ou armazém geral');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.907', 'Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.908', 'Entrada de bem por conta de contrato de comodato');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.909', 'Retorno de bem remetido por conta de contrato de comodato');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.910', 'Entrada de bonificação, doação ou brinde');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.911', 'Entrada de amostra grátis');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.912', 'Entrada de mercadoria ou bem recebido para demonstração');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.913', 'Retorno de mercadoria ou bem remetido para demonstração');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.914', 'Retorno de mercadoria ou bem remetido para exposição ou feira');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.915', 'Entrada de mercadoria ou bem recebido para conserto ou reparo');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.916', 'Retorno de mercadoria ou bem remetido para conserto ou reparo');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.917', 'Entrada de mercadoria recebida em consignação mercantil ou industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.918', 'Devolução de mercadoria remetida em consignação mercantil ou industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.919', 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.920', 'Entrada de vasilhame ou sacaria');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.921', 'Retorno de vasilhame ou sacaria');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.922', 'Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.923', 'Entrada de mercadoria recebida do vendedor remetente, em venda à ordem');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.924', 'Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.925', 'Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.926', 'Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '1.949', 'Outra entrada de mercadoria ou prestação de serviço não especificada');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.101', 'Compra para industrialização');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.102', 'Compra para comercialização');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.111', 'Compra para industrialização de mercadoria recebida anteriormente em consignação industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.113', 'Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.116', 'Compra para industrialização originada de encomenda para recebimento futuro');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.117', 'Compra para comercialização originada de encomenda para recebimento futuro');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.118', 'Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.120', 'Compra para industrialização, em venda à ordem, já recebida do vendedor remetente');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.121', 'Compra para comercialização, em venda à ordem, já recebida do vendedor remetente');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.122', 'Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.124', 'Industrialização efetuada por outra empresa');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.125', 'Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.126', 'Compra para utilização na prestação de serviço');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.151', 'Transferência para industrialização');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.152', 'Transferência para comercialização');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.153', 'Transferência de energia elétrica para distribuição');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.154', 'Transferência para utilização na prestação de serviço');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.201', 'Devolução de venda de produção do estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.202', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.203', 'Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.204', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.205', 'Anulação de valor relativo à prestação de serviço de comunicação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.206', 'Anulação de valor relativo à prestação de serviço de transporte');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.207', 'Anulação de valor relativo à venda de energia elétrica');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.208', 'Devolução de produção do estabelecimento, remetida em transferência');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.209', 'Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.251', 'Compra de energia elétrica para distribuição ou comercialização');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.252', 'Compra de energia elétrica por estabelecimento industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.253', 'Compra de energia elétrica por estabelecimento comercial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.254', 'Compra de energia elétrica por estabelecimento prestador de serviço de transporte');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.255', 'Compra de energia elétrica por estabelecimento prestador de serviço de comunicação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.256', 'Compra de energia elétrica por estabelecimento de produtor rural');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.257', 'Compra de energia elétrica para consumo por demanda contratada');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.301', 'Aquisição de serviço de comunicação para execução de serviço da mesma natureza');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.302', 'Aquisição de serviço de comunicação por estabelecimento industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.303', 'Aquisição de serviço de comunicação por estabelecimento comercial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.304', 'Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.305', 'Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.306', 'Aquisição de serviço de comunicação por estabelecimento de produtor rural');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.351', 'Aquisição de serviço de transporte para execução de serviço da mesma natureza');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.352', 'Aquisição de serviço de transporte por estabelecimento industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.353', 'Aquisição de serviço de transporte por estabelecimento comercial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.354', 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.355', 'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.356', 'Aquisição de serviço de transporte por estabelecimento de produtor rural');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.401', 'Compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.403', 'Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.406', 'Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.407', 'Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.408', 'Transferência para industrialização em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.409', 'Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.410', 'Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.411', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.414', 'Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.415', 'Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.501', 'Entrada de mercadoria recebida com fim específico de exportação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.503', 'Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.504', 'Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.551', 'Compra de bem para o ativo imobilizado');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.552', 'Transferência de bem do ativo imobilizado');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.553', 'Devolução de venda de bem do ativo imobilizado');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.554', 'Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.555', 'Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.556', 'Compra de material para uso ou consumo');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.557', 'Transferência de material para uso ou consumo');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.603', 'Ressarcimento de ICMS retido por substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.901', 'Entrada para industrialização por encomenda');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.902', 'Retorno de mercadoria remetida para industrialização por encomenda');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.903', 'Entrada de mercadoria remetida para industrialização e não aplicada no referido processo');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.904', 'Retorno de remessa para venda fora do estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.905', 'Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.906', 'Retorno de mercadoria remetida para depósito fechado ou armazém geral');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.907', 'Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.908', 'Entrada de bem por conta de contrato de comodato');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.909', 'Retorno de bem remetido por conta de contrato de comodato');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.910', 'Entrada de bonificação, doação ou brinde');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.911', 'Entrada de amostra grátis');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.912', 'Entrada de mercadoria ou bem recebido para demonstração');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.913', 'Retorno de mercadoria ou bem remetido para demonstração');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.914', 'Retorno de mercadoria ou bem remetido para exposição ou feira');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.915', 'Entrada de mercadoria ou bem recebido para conserto ou reparo');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.916', 'Retorno de mercadoria ou bem remetido para conserto ou reparo');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.917', 'Entrada de mercadoria recebida em consignação mercantil ou industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.918', 'Devolução de mercadoria remetida em consignação mercantil ou industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.919', 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.920', 'Entrada de vasilhame ou sacaria');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.921', 'Retorno de vasilhame ou sacaria');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.922', 'Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.923', 'Entrada de mercadoria recebida do vendedor remetente, em venda à ordem');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.924', 'Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.925', 'Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '2.949', 'Outra entrada de mercadoria ou prestação de serviço não especificado');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '3.101', 'Compra para industrialização');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '3.102', 'Compra para comercialização');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '3.126', 'Compra para utilização na prestação de serviço');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '3.127', 'Compra para industrialização sob o regime de "drawback"');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '3.201', 'Devolução de venda de produção do estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '3.202', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '3.205', 'Anulação de valor relativo à prestação de serviço de comunicação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '3.206', 'Anulação de valor relativo à prestação de serviço de transporte');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '3.207', 'Anulação de valor relativo à venda de energia elétrica');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '3.211', 'Devolução de venda de produção do estabelecimento sob o regime de "drawback"');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '3.251', 'Compra de energia elétrica para distribuição ou comercialização');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '3.301', 'Aquisição de serviço de comunicação para execução de serviço da mesma natureza');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '3.351', 'Aquisição de serviço de transporte para execução de serviço da mesma natureza');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '3.352', 'Aquisição de serviço de transporte por estabelecimento industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '3.353', 'Aquisição de serviço de transporte por estabelecimento comercial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '3.354', 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '3.355', 'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '3.356', 'Aquisição de serviço de transporte por estabelecimento de produtor rural');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '3.503', 'Devolução de mercadoria exportada que tenha sido recebida com fim específico de exportação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '3.551', 'Compra de bem para o ativo imobilizado');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '3.553', 'Devolução de venda de bem do ativo imobilizado');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '3.556', 'Compra de material para uso ou consumo');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '3.930', 'Lançamento efetuado a título de entrada de bem sob amparo de regime especial aduaneiro de admissão temporária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '3.949', 'Outra entrada de mercadoria ou prestação de serviço não especificado');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.101', 'Venda de produção do estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.102', 'Venda de mercadoria adquirida ou recebida de terceiros');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.103', 'Venda de produção do estabelecimento, efetuada fora do estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.104', 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.105', 'Venda de produção do estabelecimento que não deva por ele transitar');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.106', 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.109', 'Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.110', 'Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.111', 'Venda de produção do estabelecimento remetida anteriormente em consignação industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.112', 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.113', 'Venda de produção do estabelecimento remetida anteriormente em consignação mercantil');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.114', 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.115', 'Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.116', 'Venda de produção do estabelecimento originada de encomenda para entrega futura');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.117', 'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.118', 'Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.119', 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.120', 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.122', 'Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.123', 'Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.124', 'Industrialização efetuada para outra empresa');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.125', 'Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.151', 'Transferência de produção do estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.152', 'Transferência de mercadoria adquirida ou recebida de terceiros');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.153', 'Transferência de energia elétrica');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.155', 'Transferência de produção do estabelecimento, que não deva por ele transitar');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.156', 'Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.201', 'Devolução de compra para industrialização');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.202', 'Devolução de compra para comercialização');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.205', 'Anulação de valor relativo a aquisição de serviço de comunicação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.206', 'Anulação de valor relativo a aquisição de serviço de transporte');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.207', 'Anulação de valor relativo à compra de energia elétrica');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.208', 'Devolução de mercadoria recebida em transferência para industrialização');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.209', 'Devolução de mercadoria recebida em transferência para comercialização');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.210', 'Devolução de compra para utilização na prestação de serviço');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.251', 'Venda de energia elétrica para distribuição ou comercialização');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.252', 'Venda de energia elétrica para estabelecimento industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.253', 'Venda de energia elétrica para estabelecimento comercial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.254', 'Venda de energia elétrica para estabelecimento prestador de serviço de transporte');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.255', 'Venda de energia elétrica para estabelecimento prestador de serviço de comunicação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.256', 'Venda de energia elétrica para estabelecimento de produtor rural');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.257', 'Venda de energia elétrica para consumo por demanda contratada');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.258', 'Venda de energia elétrica a não contribuinte');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.301', 'Prestação de serviço de comunicação para execução de serviço da mesma natureza');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.302', 'Prestação de serviço de comunicação a estabelecimento industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.303', 'Prestação de serviço de comunicação a estabelecimento comercial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.304', 'Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.305', 'Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.306', 'Prestação de serviço de comunicação a estabelecimento de produtor rural');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.307', 'Prestação de serviço de comunicação a não contribuinte');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.351', 'Prestação de serviço de transporte para execução de serviço da mesma natureza');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.352', 'Prestação de serviço de transporte a estabelecimento industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.353', 'Prestação de serviço de transporte a estabelecimento comercial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.354', 'Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.355', 'Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.356', 'Prestação de serviço de transporte a estabelecimento de produtor rural');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.357', 'Prestação de serviço de transporte a não contribuinte');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.401', 'Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.402', 'Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.403', 'Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.405', 'Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituído');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.408', 'Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.409', 'Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.410', 'Devolução de compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.411', 'Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.412', 'Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.413', 'Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.414', 'Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.415', 'Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.451', 'Remessa de animal e de insumo para estabelecimento produtor');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.501', 'Remessa de produção do estabelecimento, com fim específico de exportação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.502', 'Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.503', 'Devolução de mercadoria recebida com fim específico de exportação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.551', 'Venda de bem do ativo imobilizado');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.552', 'Transferência de bem do ativo imobilizado');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.553', 'Devolução de compra de bem para o ativo imobilizado');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.554', 'Remessa de bem do ativo imobilizado para uso fora do estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.555', 'Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.556', 'Devolução de compra de material de uso ou consumo');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.557', 'Transferência de material de uso ou consumo');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.601', 'Transferência de crédito de ICMS acumulado');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.602', 'Transferência de saldo credor de ICMS para outro estabelecimento da mesma empresa, destinado à compensação de saldo devedor de ICMS');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.603', 'Ressarcimento de ICMS retido por substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.901', 'Remessa para industrialização por encomenda');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.902', 'Retorno de mercadoria utilizada na industrialização por encomenda');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.903', 'Retorno de mercadoria recebida para industrialização e não aplicada no referido processo');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.904', 'Remessa para venda fora do estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.905', 'Remessa para depósito fechado ou armazém geral');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.906', 'Retorno de mercadoria depositada em depósito fechado ou armazém geral');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.907', 'Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.908', 'Remessa de bem por conta de contrato de comodato');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.909', 'Retorno de bem recebido por conta de contrato de comodato');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.910', 'Remessa em bonificação, doação ou brinde');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.911', 'Remessa de amostra grátis');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.912', 'Remessa de mercadoria ou bem para demonstração');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.913', 'Retorno de mercadoria ou bem recebido para demonstração');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.914', 'Remessa de mercadoria ou bem para exposição ou feira');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.915', 'Remessa de mercadoria ou bem para conserto ou reparo');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.916', 'Retorno de mercadoria ou bem recebido para conserto ou reparo');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.917', 'Remessa de mercadoria em consignação mercantil ou industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.918', 'Devolução de mercadoria recebida em consignação mercantil ou industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.919', 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.920', 'Remessa de vasilhame ou sacaria');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.921', 'Devolução de vasilhame ou sacaria');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.922', 'Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.923', 'Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.924', 'Remessa para industrialização por conta e ordem do adquirente da mercadoria,');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.925', 'Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.926', 'Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.927', 'Lançamento efetuado a título de baixa de estoque decorrente de perda, roubo ou deterioração');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.928', 'Lançamento efetuado a título de baixa de estoque decorrente do encerramento da atividade da empresa');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.929', 'Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.931', 'Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.932', 'Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '5.949', 'Outra saída de mercadoria ou prestação de serviço não especificado');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.101', 'Venda de produção do estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.102', 'Venda de mercadoria adquirida ou recebida de terceiros');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.103', 'Venda de produção do estabelecimento, efetuada fora do estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.104', 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.105', 'Venda de produção do estabelecimento que não deva por ele transitar');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.106', 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.107', 'Venda de produção do estabelecimento, destinada a não contribuinte');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.108', 'Venda de mercadoria adquirida ou recebida de terceiros, destinada a não contribuinte');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.109', 'Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.110', 'Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.111', 'Venda de produção do estabelecimento remetida anteriormente em consignação industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.112', 'Venda de mercadoria adquirida ou recebida de Terceiros remetida anteriormente em consignação industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.113', 'Venda de produção do estabelecimento remetida anteriormente em consignação mercantil');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.114', 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.115', 'Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.116', 'Venda de produção do estabelecimento originada de encomenda para entrega futura');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.117', 'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.118', 'Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.119', 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.120', 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.122', 'Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.123', 'Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.124', 'Industrialização efetuada para outra empresa');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.125', 'Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.151', 'Transferência de produção do estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.152', 'Transferência de mercadoria adquirida ou recebida de terceiros');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.153', 'Transferência de energia elétrica');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.155', 'Transferência de produção do estabelecimento, que não deva por ele transitar');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.156', 'Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.201', 'Devolução de compra para industrialização');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.202', 'Devolução de compra para comercialização');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.205', 'Anulação de valor relativo a aquisição de serviço de comunicação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.206', 'Anulação de valor relativo a aquisição de serviço de transporte');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.207', 'Anulação de valor relativo à compra de energia elétrica');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.208', 'Devolução de mercadoria recebida em transferência para industrialização');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.209', 'Devolução de mercadoria recebida em transferência para comercialização');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.210', 'Devolução de compra para utilização na prestação de serviço');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.251', 'Venda de energia elétrica para distribuição ou comercialização');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.252', 'Venda de energia elétrica para estabelecimento industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.253', 'Venda de energia elétrica para estabelecimento comercial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.254', 'Venda de energia elétrica para estabelecimento prestador de serviço de transporte');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.255', 'Venda de energia elétrica para estabelecimento prestador de serviço de comunicação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.256', 'Venda de energia elétrica para estabelecimento de produtor rural');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.257', 'Venda de energia elétrica para consumo por demanda contratada');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.258', 'Venda de energia elétrica a não contribuinte');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.301', 'Prestação de serviço de comunicação para execução de serviço da mesma natureza');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.302', 'Prestação de serviço de comunicação a estabelecimento industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.303', 'Prestação de serviço de comunicação a estabelecimento comercial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.304', 'Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.305', 'Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.306', 'Prestação de serviço de comunicação a estabelecimento de produtor rural');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.307', 'Prestação de serviço de comunicação a não contribuinte');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.351', 'Prestação de serviço de transporte para execução de serviço da mesma natureza');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.352', 'Prestação de serviço de transporte a estabelecimento industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.353', 'Prestação de serviço de transporte a estabelecimento comercial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.354', 'Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.355', 'Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.356', 'Prestação de serviço de transporte a estabelecimento de produtor rural');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.357', 'Prestação de serviço de transporte a não contribuinte');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.401', 'Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.402', 'Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.403', 'Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.404', 'Venda de mercadoria sujeita ao regime de substituição tributária, cujo imposto já tenha sido retido anteriormente');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.408', 'Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.409', 'Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.410', 'Devolução de compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.411', 'Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.412', 'Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.413', 'Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.414', 'Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.415', 'Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.501', 'Remessa de produção do estabelecimento, com fim específico de exportação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.502', 'Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.503', 'Devolução de mercadoria recebida com fim específico de exportação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.551', 'Venda de bem do ativo imobilizado');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.552', 'Transferência de bem do ativo imobilizado');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.553', 'Devolução de compra de bem para o ativo imobilizado');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.554', 'Remessa de bem do ativo imobilizado para uso fora do estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.555', 'Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.556', 'Devolução de compra de material de uso ou consumo');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.557', 'Transferência de material de uso ou consumo');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.603', 'Ressarcimento de ICMS retido por substituição tributária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.901', 'Remessa para industrialização por encomenda');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.902', 'Retorno de mercadoria utilizada na industrialização por encomenda');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.903', 'Retorno de mercadoria recebida para industrialização e não aplicada no referido processo');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.904', 'Remessa para venda fora do estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.905', 'Remessa para depósito fechado ou armazém geral');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.906', 'Retorno de mercadoria depositada em depósito fechado ou armazém geral');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.907', 'Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.908', 'Remessa de bem por conta de contrato de comodato');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.909', 'Retorno de bem recebido por conta de contrato de comodato');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.910', 'Remessa em bonificação, doação ou brinde');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.911', 'Remessa de amostra grátis');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.912', 'Remessa de mercadoria ou bem para demonstração');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.913', 'Retorno de mercadoria ou bem recebido para demonstração');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.914', 'Remessa de mercadoria ou bem para exposição ou feira');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.915', 'Remessa de mercadoria ou bem para conserto ou reparo');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.916', 'Retorno de mercadoria ou bem recebido para conserto ou reparo');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.917', 'Remessa de mercadoria em consignação mercantil ou industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.918', 'Devolução de mercadoria recebida em consignação mercantil ou industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.919', 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.920', 'Remessa de vasilhame ou sacaria');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.921', 'Devolução de vasilhame ou sacaria');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.922', 'Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.923', 'Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.924', 'Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.925', 'Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.929', 'Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.931', 'Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.932', 'Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '6.949', 'Outra saída de mercadoria ou prestação de serviço não especificado');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '7.101', 'Venda de produção do estabelecimento');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '7.102', 'Venda de mercadoria adquirida ou recebida de terceiros');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '7.105', 'Venda de produção do estabelecimento, que não deva por ele transitar');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '7.106', 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '7.127', 'Venda de produção do estabelecimento sob o regime de "drawback"');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '7.201', 'Devolução de compra para industrialização');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '7.202', 'Devolução de compra para comercialização');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '7.205', 'Anulação de valor relativo à aquisição de serviço de comunicação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '7.206', 'Anulação de valor relativo a aquisição de serviço de transporte');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '7.207', 'Anulação de valor relativo à compra de energia elétrica');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '7.210', 'Devolução de compra para utilização na prestação de serviço');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '7.211', 'Devolução de compras para industrialização sob o regime de drawback"');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '7.251', 'Venda de energia elétrica para o exterior');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '7.301', 'Prestação de serviço de comunicação para execução de serviço da mesma natureza');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '7.358', 'Prestação de serviço de transporte');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '7.501', 'Exportação de mercadorias recebidas com fim específico de exportação');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '7.551', 'Venda de bem do ativo imobilizado');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '7.553', 'Devolução de compra de bem para o ativo imobilizado');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '7.556', 'Devolução de compra de material de uso ou consumo');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '7.930', 'Lançamento efetuado a título de devolução de bem cuja entrada tenha ocorrido sob amparo de regime especial aduaneiro de admissão temporária');
INSERT INTO cygni.cfop (IdCfop, Code, Nome) VALUES (nextval('cygni.SEQ_cfop'), '7.949', 'Outra saída de mercadoria ou prestação de serviço não especificado');
